import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Watch, validIMO, timestamp, freshness} from '../backend/core.js';
import {Store} from '../backend/storage.js';
const fleet=JSON.parse(fs.readFileSync(new URL('../public/data/fleet.json',import.meta.url)));
const zones=[{id:'genova',name:'Genova',country:'Italia',lat:44.4,lon:8.91,radius_nm:3}];
const now=()=>new Date().toISOString();
function message(type,body,at=now()){return {MessageType:type,MetaData:{MMSI:440161000,ShipName:'GLOVIS CORONA',time_utc:at,latitude:44.4,longitude:8.91},Message:{[type]:body}};}
function verified(w){w.ingestStream(message('ShipStaticData',{ImoNumber:9122930,Name:'GLOVIS CORONA'}),'AISStream');return w.rows.get('9122930');}
test('44 unique fleet entries and Equasis role counts / wrapped ship names',()=>{assert.equal(fleet.vessels.length,44);assert.equal(new Set(fleet.vessels.map(v=>v.imo)).size,44);assert.equal(fleet.vessels.filter(v=>v.company_roles.includes('Registered owner')).length,39);assert.equal(fleet.vessels.filter(v=>v.company_roles.includes('Ship manager / Commercial manager')).length,41);assert.equal(fleet.vessels.find(v=>v.imo==='9904089').name,'VL RENAISSANCE');assert.equal(fleet.vessels.find(v=>v.imo==='9975040').name,'WOODSIDE SCARLET IBIS');for(const v of fleet.vessels)assert.equal(validIMO(v.imo),v.imo);});
test('same vessel name does not verify an IMO or expose a position',()=>{const w=new Watch(fleet,zones);w.ingestStream(message('PositionReport',{Latitude:44.4,Longitude:8.91,Sog:0}),'AISStream');assert.equal(w.snapshot().summary.identified,0);assert.equal(w.rows.get('9122930').position,null);});
test('static message identifies IMO but cannot refresh cached coordinates',()=>{const w=new Watch(fleet,zones),r=verified(w);assert.equal(r.identity.mmsi,'440161000');assert.equal(r.position,null);const at=new Date(Date.now()-3600000).toISOString();w.ingestStream(message('PositionReport',{Latitude:44.4,Longitude:8.91,Sog:0},at),'AISStream');assert.equal(freshness(r.position),'stale');w.ingestStream(message('ShipStaticData',{ImoNumber:9122930,Destination:'GENOA'}),'AISStream');assert.equal(r.position.at,at);assert.equal(freshness(r.position),'stale');assert.equal(w.events.filter(e=>e.type.startsWith('area_')).length,0);});
test('invalid coordinates, missing timestamps and AIS sentinels handled',()=>{const w=new Watch(fleet,zones),r=verified(w);w.ingestStream(message('PositionReport',{Latitude:91,Longitude:181}),'AISStream');assert.equal(r.position,null);w.ingestStream(message('PositionReport',{Latitude:null,Longitude:null}),'AISStream');assert.equal(r.position,null);w.ingestStream(message('PositionReport',{Latitude:44.4,Longitude:8.91,Sog:102.3,Cog:360,TrueHeading:511}),'AISStream');assert.equal(r.position.sog,null);assert.equal(r.position.cog,null);assert.equal(r.position.heading,null);assert.equal(timestamp(null),null);});
test('first area observation and continuous exit/entry are distinguished',()=>{const w=new Watch(fleet,zones),r=verified(w);let t=Date.now()-180000;w.applyPosition(r,{lat:44.4,lon:8.91,at:new Date(t).toISOString(),sog:0});assert.equal(w.events.at(-1).type,'area_observed');t+=60000;w.applyPosition(r,{lat:44.3,lon:8.91,at:new Date(t).toISOString(),sog:14});assert.equal(w.events.at(-1).type,'area_exit');t+=60000;w.applyPosition(r,{lat:44.4,lon:8.91,at:new Date(t).toISOString(),sog:14});assert.equal(w.events.at(-1).type,'area_enter');});
test('IMO conflict clears old identity and old position',()=>{const w=new Watch(fleet,zones),r=verified(w);w.applyPosition(r,{lat:44.4,lon:8.91,at:now()});w.identify('440161000','9122942','test',now());assert.equal(r.identity,null);assert.equal(r.position,null);assert.equal(w.byMMSI.get('440161000'),'9122942');});
test('stale reports do not overwrite newer position; implausible jumps are flagged',()=>{const w=new Watch(fleet,zones),r=verified(w),at=now();w.applyPosition(r,{lat:44.4,lon:8.91,at});assert.equal(w.applyPosition(r,{lat:10,lon:10,at:new Date(Date.parse(at)-1000).toISOString()}),false);assert.equal(w.applyPosition(r,{lat:10,lon:10,at:new Date(Date.parse(at)+1000).toISOString()}),false);assert.equal(w.events.at(-1).type,'position_outlier');assert.equal(r.position.lat,44.4);});
test('archive round trip preserves identities, positions and events',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vw-'));try{const w=new Watch(fleet,zones),r=verified(w);w.applyPosition(r,{lat:44.4,lon:8.91,at:now()});const store=new Store(dir);store.save(w);assert.equal(store.error,null);const loaded=new Watch(fleet,zones,store.load());assert.equal(loaded.rows.get(r.imo).history.length,1);assert.equal(loaded.byMMSI.get('440161000'),r.imo);assert.equal(loaded.events.length,w.events.length);}finally{fs.rmSync(dir,{recursive:true});}});
test('old snapshot may populate an empty position for the same verified IMO/MMSI',()=>{const w=new Watch(fleet,zones),r=verified(w),at=new Date(Date.now()-86400000).toISOString();assert.equal(w.ingestFeature({id:440161000,geometry:{type:'Point',coordinates:[8.91,44.4]},properties:{mmsi:440161000,imo:9122930,seen:at,name:'GLOVIS CORONA',sog:0}},true),true);assert.equal(r.position.at,at);assert.notEqual(freshness(r.position),'recent');});
